---
title: "To-do"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Decisions:  

-  what exactly should the data frame look like going into the multivariate analyses  
-  how many dimensions to use for NMDS (currently using 3)  
-  do we need to adjust p-values for the post-permanova comparisons?  
-  which nesting structure to use for mixed models (univariate)  
-  do we want to keep "top 3" plots 
-  do we want richness and diversity for each plot on each date? can use in univariate analyses  
-  should EIR be included in the multivariate analyses, as a column in the response matrix? (currently it is, after being multiplied by 100 to get it on the same scale as species covers)  
    
### Documentation:   

-  add response to plot titles in univariate analyses  
-  remove quilt plot once univariate modeling decisions are made    
-  add more descriptive model names and information, particularly for the part where errors will show up    
-  print which species are within each category used in the anaSpec_df data frames - or each application (spatial plots, univariate responses, multivariate responses)  
-  make a glossary about how code chunks are named (read, source, define, mod, graph, stats)  
    
### Other:  

-  after exploration but before statistical analyses, remove any plots without at least [X] readings.  
-  clean up permanova and simper output  
-  fix the weird years issue with the bar plots  
-  univariate analyses might barf if a reserve doesn't specify at least 3 species or groups. If they provided 3 but not 4, I automatically pull a species from the "top 5 by mean" that was not otherwise named.    
-  figure out how to look at the provided Plant_Categories and see if any species were removed because they were named separately - and if so, rename it to "Other category]" in all anaSpec_df data frames  
-  move "other" (and unvegetated, if present) to end of list of species for legends etc.  
-  add flexibility to which QA/QC flags get removed  
-  Need to do something about NMST abiotic categories, unknown species, unvegetated, etc. Probably want data frames by:  
   -  species (original)  
   -  vegetation group  
   -  with custom metrics  
-  make a script to install necessary packages, and a script to make sure packages are installed and loading  
-  general documentation on how a reserve can run this - will be a single script calling parent .Rmd; actually should be easier for Reserves than SETr  
-  NMDS - add points/lines for species  