---
title: "Veg Analysis"
output: 
    html_document:
        toc: true
        toc_float: true
params: 
    file_code: "GND"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      error = TRUE)
```

```{r, message = FALSE, warning = FALSE}
library(dplyr)
library(tidyr)
library(readxl)
library(stringr)
library(kableExtra)
library(DT)
source("sourced/functions.R")

file_dat <- here::here("data", paste0(params$file_code, "_NMST.xlsx"))
file_specs <- here::here("metadata", paste0(params$file_code, "veg_specs.xlsx"))
```

```{r}
# read data

dat <- get_data(file_dat, cover_only = TRUE) # gets rid of density and height columns; keeps F_ columns
stn_tbl <- get_stn_table(file_dat)
species_info <- get_species_info(file_dat)
eis <- get_ecotone_invaders(file = file_specs)
```


# QA/QC  

```{r, child = "sourced/001_QAQC.Rmd"}

```


# Summary Figures  

```{r, child = "sourced/002_Summary_Figures.Rmd"}

```


# Univariate Analyses  

```{r, child = "sourced/003_Univariate_Analyses.Rmd"}

```


# Multivariate Analyses  

```{r, child = "sourced/004_Multivariate_Analyses.Rmd"}

```

